### ISSUE TITLE
Support dark mode

### ISSUE THREAD

**Issue by jiacai2050** [yihui/hugo-xmin#67]

**Comment by yihui** [comment]
自己动手，丰衣足食。极简风格的暗黑模式并不太难，我常用的偷懒办法就是把背景色设置为白色之后把整个页面的颜色全盘反转：

```css
@media (prefers-color-scheme: dark) {
  body {
    background-color: white;
  }
  html, img, video, iframe {
    filter: invert(1);
  }
}
```

当然，肯定还有些细节需要调整。给你个参考示例：https://github.com/yihui/hugo-paged/blob/main/static/css/style.css
